finishing up basic get requests
cornell-dti/club-view pull request #16
Opened 2022-02-09 01:00 UTC by justinkang01

### Summary 

This pull request is the first step towards implementing the basic api endpoints for the Students

- [x] implemented get all students
- [x] implemented get student by ID
- [x] implemented get favorite clubs of a student
### Test Plan 

Accessed endpoints on localhost to check for proper responses for each get request.

### Notes 

### Breaking Changes  

<!-- - Database schema change (anything that changes DynamoDB document structure)
<!-- - Other change that could cause problems (Detailed in notes)

2022-02-11 07:17 UTC, aaronkang7 requested changes, later dismissed

2022-02-11 07:17 UTC, aaronkang7 commented on backend/router/student.ts
>  });
Great job on making the endpoints! But, I'm sorry if it wasn't clear in the task description, but the getfavorites endpoint should return and array with whole club objects inside of them! Other than that, great job :). Also, make sure to pull changes in from the origin before merging!

2022-03-20 20:21 UTC, JustKong13 approved these changes, later dismissed
I like the reorganization of the file and how everything's a bit more consistent now. Everything works for me!

2022-03-23 13:21 UTC, justinkang01 commented
the changes i've made are mostly to the student.ts file. When getting a student from the endpoint, i originally made it so that only the names of the clubs are being sent instead of the club objects. this new code uses firestore document references to reference the clubs so that a student's favorites as well as their managed clubs all return objects of clubtype (using the actual club documents in the clubs collection). This means that we can edit the clubs.ts file to do a similar thing where the registedBy field can be a reference to a student document instead of just a name. another thing to mention is that maybe we can add validate functions in a utils.tsx file to validate if a club or student exists. idk how often we might use it but it could be something to make our code more modular

2022-03-29 23:40 UTC, 20austinw approved these changes
Looks pretty good!

2022-03-29 23:41 UTC, merged